### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by Yumash** [jack-karamanian/vscode-perlsyntax#1]
> events.js:163
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write EPIPE
>     at exports._errnoException (util.js:1050:11)
>     at Socket._writeGeneric (net.js:724:26)
>     at Socket._write (net.js:743:8)
>     at doWrite (_stream_writable.js:329:12)
>     at writeOrBuffer (_stream_writable.js:315:5)
>     at Socket.Writable.write (_stream_writable.js:241:11)
>     at Socket.write (net.js:670:40)
>     at PerlLinter.lint (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\PerlLinter.js:22:23)
>     at validateTextDocument (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\server.js:55:12)
>     at documents.onDidChangeContent.lodash_1.debounce (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\server.js:35:5)
> [Info  - 10:17:35] Connection to server got closed. Server will restart.
> events.js:163
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write EPIPE
>     at exports._errnoException (util.js:1050:11)
>     at Socket._writeGeneric (net.js:724:26)
>     at Socket._write (net.js:743:8)
>     at doWrite (_stream_writable.js:329:12)
>     at writeOrBuffer (_stream_writable.js:315:5)
>     at Socket.Writable.write (_stream_writable.js:241:11)
>     at Socket.write (net.js:670:40)
>     at PerlLinter.lint (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\PerlLinter.js:22:23)
>     at validateTextDocument (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\server.js:55:12)
>     at documents.onDidChangeContent.lodash_1.debounce (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\server.js:35:5)
> [Info  - 10:17:37] Connection to server got closed. Server will restart.
> events.js:163
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write EPIPE
>     at exports._errnoException (util.js:1050:11)
>     at Socket._writeGeneric (net.js:724:26)
>     at Socket._write (net.js:743:8)
>     at doWrite (_stream_writable.js:329:12)
>     at writeOrBuffer (_stream_writable.js:315:5)
>     at Socket.Writable.write (_stream_writable.js:241:11)
>     at Socket.write (net.js:670:40)
>     at PerlLinter.lint (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\PerlLinter.js:22:23)
>     at validateTextDocument (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\server.js:55:12)
>     at documents.onDidChangeContent.lodash_1.debounce (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\server.js:35:5)
> [Info  - 10:17:39] Connection to server got closed. Server will restart.
> events.js:163
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write EPIPE
>     at exports._errnoException (util.js:1050:11)
>     at Socket._writeGeneric (net.js:724:26)
>     at Socket._write (net.js:743:8)
>     at doWrite (_stream_writable.js:329:12)
>     at writeOrBuffer (_stream_writable.js:315:5)
>     at Socket.Writable.write (_stream_writable.js:241:11)
>     at Socket.write (net.js:670:40)
>     at PerlLinter.lint (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\PerlLinter.js:22:23)
>     at validateTextDocument (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\server.js:55:12)
>     at documents.onDidChangeContent.lodash_1.debounce (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\server.js:35:5)
> [Info  - 10:17:40] Connection to server got closed. Server will restart.
> events.js:163
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write EPIPE
>     at exports._errnoException (util.js:1050:11)
>     at Socket._writeGeneric (net.js:724:26)
>     at Socket._write (net.js:743:8)
>     at doWrite (_stream_writable.js:329:12)
>     at writeOrBuffer (_stream_writable.js:315:5)
>     at Socket.Writable.write (_stream_writable.js:241:11)
>     at Socket.write (net.js:670:40)
>     at PerlLinter.lint (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\PerlLinter.js:22:23)
>     at validateTextDocument (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\server.js:55:12)
>     at documents.onDidChangeContent.lodash_1.debounce (C:\Users\andre\.vscode\extensions\jackkaramanian.perl-syntax-0.0.4\server\server.js:35:5)
> [Error - 10:17:44] Connection to server got closed. Server will not be restarted.

![image](https://user-images.githubusercontent.com/6568685/32823507-844bf57a-c9ee-11e7-8b38-faa7f2824b9e.png)

**Comment by Yumash** [comment]
VSC: V1.18.0 x64, Windows 10. Perl 5.24.

**Comment by jack-karamanian** [comment]
@Yumash 
It looks like you're missing a \ in the executable path.

**Comment by Yumash** [comment]
Ah, now i see. Strange that VS Code didnt show me it with red. Sorry for inconvinience!

**Comment by eych** [comment]
I have the same issue on Mac with High Sierra 10.13.2 and standard Perl v5.18.2, VS Code 1.19.1.

```events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
[Info  - 10:43:13 AM] Connection to server got closed. Server will restart.
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
[Info  - 10:43:18 AM] Connection to server got closed. Server will restart.
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
[Info  - 10:43:20 AM] Connection to server got closed. Server will restart.
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
[Info  - 10:43:22 AM] Connection to server got closed. Server will restart.
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
[Error - 10:43:24 AM] Connection to server got closed. Server will not be restarted.
```

I am using standard perlSyntax config that came with the extension (with `perl` being the executable specified).

**Comment by jack-karamanian** [comment]
@eych,
How long (in lines) is the file?

**Comment by jack-karamanian** [comment]
This should be fixed in the latest version.
It splits the text into parts of 1000 characters, and writes those to the Perl process, instead of the entire string at once.

Let me know if you encounter this again.

**Comment by eych** [comment]
Thanks for looking into this!

You are right that this is connected to the size of the file. I've tried it on a really small Perl module and it worked fine. However, I still have the same problem with a file that is 858 lines long using your latest version (0.0.5).

**Comment by eych** [comment]
Actually, it works when I specify the include paths for the libs that I use in the extension settings. It's only crashing on that bigger file when I don't specify any include lib and just use the default empty setting for this which came with the extension.

**Comment by jack-karamanian** [comment]
I found the crash to occur when Perl finds too many syntax errors. In this case, Perl exits, and any writes to its stdin fail, causing the extension to crash. This should be fixed in the latest version.
